config/routes.rb
Karaharapriya::Application.routes.draw do

  devise_for :users

  root :to => "home#index"

  resources :ragams, :songs, :talams, :composers, :except => [:destroy]

  match "suggest/ragam" => "ragams#suggest", :as => "suggest_ragam"
  match "suggest/talam" => "talams#suggest", :as => "suggest_talam"
  match "suggest/composer" => "composers#suggest", :as => "suggest_composer"
end

app/models/composer.rb
class Composer
  include Mongoid::Document
  include Mongoid::Globalize
  include Suggest

  field :name, :type => Hash
  field :century, :type => Hash

  validates_presence_of :name
  validates_uniqueness_of :name
  translate :name, :century

  def to_param
    self.name
  end

end

app/controllers/composers_controller.rb
class ComposersController < AuthenticatableController

  before_filter :load_composer, :only => [:edit, :update, :show]

  def index
    @composers = Composer.all
  end

  def new
    @composer = Composer.new
  end

  def create
    composer = Composer.create(params[:composer])
    render_custom_response RemoteResponse.new(composer, composers_path)
  end

  def update
    @composer.update_attributes(params[:composer])
    render_custom_response RemoteResponse.new(@composer, composers_path)
  end

  def suggest
    render :partial => "common/suggest", :locals => { :suggestions => Composer.suggest_by_name(params[:name]), :name => "composer" }
  end

  private

  def load_composer
    @composer = Composer.find_by_translated_field("name", params[:id])
  end

end

app/views/composers/_form.html.haml
= form_for composer, :remote => true do |f|
  .header
    .bread_crumbs= form_title
  .body
    .sidebar
      .flash_notice{"data-error-info" => "true"}
      .error{"data-error-display" => "true"}
    %dl
      %dt= f.label :name, t(:name)
      %dd= f.text_field :name
      %dt= f.label :century, t(:century)
      %dd= f.text_field :century
    = submit_tag t(:submit)
    .clear

app/views/composers/edit.html.haml
= render 'form', :composer => @composer, :form_title => "Editing #{t(:composer).downcase} #{@composer.name}"

app/views/composers/index.html.haml
.header
  .action
    = link_to t(:new_composer), new_composer_path
  .bread_crumbs= t(:composer)
  .clear
.body
  %table{:cellspacing => "0", :cellpadding => "0"}
    %thead
      %tr
        %th Name
        %th Century
        %th
    %tbody
      -@composers.each do |composer|
        %tr
          %td= link_to composer.name, composer_path(composer)
          %td= composer.century
          %td
            [
            = link_to :edit, edit_composer_path(composer)
            ]

app/views/composers/new.html.haml
= render 'form', :composer => @composer, :form_title => "Create a new #{t :composer}"

app/views/composers/show.html.haml
.header
  .bread_crumbs="#{t(:composer)} #{@composer.name}"
.body
  .sidebar
    .flash_notice
    .error
  %dl
    %dt= t(:name)
    %dd= @composer.name
    %dt= t(:century)
    %dd= @composer.century