config/routes.rb
Karaharapriya::Application.routes.draw do

  devise_for :users

  root :to => "home#index"

  resources :ragams, :songs, :talams, :composers, :except => [:destroy]

  match "suggest/ragam" => "ragams#suggest", :as => "suggest_ragam"
  match "suggest/talam" => "talams#suggest", :as => "suggest_talam"
  match "suggest/composer" => "composers#suggest", :as => "suggest_composer"
end

app/models/song.rb
class Song
  include Mongoid::Document
  include Mongoid::Globalize

  field :name, :type => Hash
  field :content, :type => Hash
  referenced_in :song_type
  referenced_in :ragam
  referenced_in :talam
  referenced_in :composer

  validates_presence_of :name, :content, :ragam, :talam, :song_type
  validates_uniqueness_of :name
  translate :name, :content

  def self.find_by_id id
    Song.first(:conditions => {:id => id})
  end

  def to_param
    self.name
  end

end

app/models/song_type.rb
class SongType
  include Mongoid::Document
  include Sorter

  field :name
  field :description
  validates_uniqueness_of :name
end

app/controllers/songs_controller.rb
class SongsController < AuthenticatableController

  before_filter :load_song_types, :only => [:new, :edit]
  before_filter :load_song, :only => [:edit, :update, :show]
  before_filter :remove_first_class_params, :only => [:create, :update]

  def index
    @songs = Song.includes(:ragam, :talam, :composer).all
  end

  def new
    @song = Song.new
  end

  def create
    song = Song.create(params[:song])
    render_custom_response RemoteResponse.new(song, songs_path)
  end

  def update
    @song.update_attributes(params[:song])
    render_custom_response RemoteResponse.new(@song, songs_path)
  end

  private

  def remove_first_class_params
    [:composer,:ragam,:talam].each {|key| params[:song].delete(key)}
  end

  def load_song_types
    @song_types = SongType.all
  end

  def load_song
    @song = Song.find_by_translated_field("name", params[:id])
  end

end

app/helpers/songs_helper.rb
module SongsHelper

  def editor options, &block
    render :partial => 'common/song_editor', :locals => {:url => options[:url], :song_type => options[:song_type], :body => capture(&block), :class_name => options[:class]}
  end

end

app/views/songs/_form.html.haml
=form_for song, :remote => true do |f|
  -song_type = song.song_type.nil? ? nil : song.song_type.id
  -composer_name = song.composer.nil? ? nil : song.composer.name
  -ragam_name = song.ragam.nil? ? nil : song.ragam.name
  -talam_name = song.talam.nil? ? nil : song.talam.name

  .header
    .bread_crumbs= form_title

  .body
    .sidebar
      .flash_notice{"data-error-info" => "true"}
      .error{"data-error-display" => "true"}
    %dl
      %dt= f.label :name, t(:name)
      %dd= f.text_field :name
      %dt= f.label :song_type, t(:song_type)
      %dd= f.select :song_type , options_for_select(song_types.collect{ |type| [type.name, type.id] }, song_type), :include_blank => "-#{t :select}-" 

    =auto_complete :label => t(:composer), :field_name => "composer", :name => "composer_id", :url => suggest_composer_path, :value => composer_name, :form_helper => f
    =auto_complete :label => t(:ragam), :field_name => "ragam", :name => "ragam_id", :url => suggest_ragam_path, :value => ragam_name, :form_helper => f
    =auto_complete :label => t(:talam), :field_name => "talam", :name => "talam_id", :url => suggest_talam_path, :value => talam_name, :form_helper => f

    %dl
      %dt= f.label :content, t(:content)
      %dd= f.text_area "content", :class => "rich_editor"

    = submit_tag t(:submit)
    .clear

app/views/songs/edit.html.haml
-form_title = "Editing #{@song.name} #{t(:song).downcase}"
=render('form', :song => @song, :song_types => @song_types, :form_title => form_title)

app/views/songs/index.html.haml
.header
  .action
    =link_to t(:new_song), new_song_path
  .bread_crumbs= t(:song)
  .clear

.body
  %table{:cellpadding => "0", :cellspacing => "0"}
    %thead
      %tr
        %th Name
        %th Composer
        %th Ragam
        %th Talam
        %th
    %tbody
      - @songs.each do |song|
        %tr
          %td= link_to song.name, song_path(song)
          %td= song.composer.nil? ? "" : song.composer.name
          %td= song.ragam.nil? ? "" : song.ragam.name
          %td= song.talam.nil? ? "" : song.talam.name
          %td
            [
            =link_to :edit, edit_song_path(song)
            ]

app/views/songs/new.html.haml
-form_title = "Create a new #{t :song}"
=render('form', :song => @song, :song_types => @song_types, :form_title => form_title)

app/views/songs/show.html.haml
.header
  .bread_crumbs="#{t(:song)} #{@song.name}"
.body
  .sidebar
    .flas_notice
    .error
  %dl
    %dt= t(:name)
    %dd= @song.name
    %dt= t(:song_type)
    %dd= @song.song_type.name
    %dt= t(:ragam)
    %dd= @song.ragam.name
    %dt= t(:talam)
    %dd= @song.talam.name
    %dt= t(:composer)
    %dd= @song.composer.name
    %dt= t(:content)
    %dd= @song.content