config/routes.rb
Karaharapriya::Application.routes.draw do

  devise_for :users

  root :to => "home#index"

  resources :ragams, :songs, :talams, :composers, :except => [:destroy]

  match "suggest/ragam" => "ragams#suggest", :as => "suggest_ragam"
  match "suggest/talam" => "talams#suggest", :as => "suggest_talam"
  match "suggest/composer" => "composers#suggest", :as => "suggest_composer"
end

app/models/talam.rb
class Talam
  include Mongoid::Document
  include Mongoid::Globalize
  include Suggest

  field :name, :type => Hash
  field :avartanam
  field :laghu_length, :type => Integer

  validates_presence_of :name, :avartanam, :laghu_length
  validates_uniqueness_of :name
  validates_uniqueness_of :laghu_length, :through => :avartanam

  validate :validate_avartanam
  translate :name

  def akshram_length_map
    @akshram_length_map ||= {"1" => self.laghu_length, "0" => 2, "U" => 1}
  end

  def validate_avartanam
    return if avartanam.blank?
    errors.add(:avartanam, "has invalid character") unless (avartanam.split(' ') - akshram_length_map.keys).empty?
  end

  def total_aksharam_length
    length = 0;
    avartanam.split(' ').each { |lagu_drutham| length += aksharam_length(lagu_drutham) } unless avartanam.blank?
    return length
  end

  def aksharam_length(key)
    akshram_length_map[key]
  end

  def to_param
    self.name
  end

end

app/controllers/talams_controller.rb
class TalamsController < AuthenticatableController

  before_filter :load_talam, :only => [:edit, :update, :show]

  def index
    @talams = Talam.all
  end

  def new
    @talam = Talam.new
  end

  def create
    talam = Talam.create(params[:talam])
    render_custom_response RemoteResponse.new(talam, talams_path)
  end

  def update
    @talam.update_attributes(params[:talam])
    render_custom_response RemoteResponse.new(@talam, talams_path)
  end

  def suggest
    render :partial => "common/suggest", :locals => { :suggestions => Talam.suggest_by_name(params[:name]), :name => "talam" }
  end

  private

  def load_talam
    @talam = Talam.find_by_translated_field("name", params[:id])
  end

end

app/views/talams/_form.html.haml
= form_for talam, :remote => true do |f|
  .header
    .bread_crumbs= form_title

  .body
    .sidebar
      .flash_notice{"data-error-info" => "true"}
      .error{"data-error-display" => "true"}
    %dl
      %dt= f.label :name, t(:name)
      %dd= f.text_field :name
      %dt= f.label :avartanam, t(:avartanam)
      %dd= f.text_field :avartanam
      %dt= f.label :laghu_length, t(:laghu_length)
      %dd= f.text_field :laghu_length

    =submit_tag t(:submit)
    .clear

app/views/talams/edit.html.haml
= render 'form', :talam => @talam, :form_title => "Editing #{@talam.name} #{t(:talam).downcase}"

app/views/talams/index.html.haml
.header
  .action
    = link_to t(:new_talam), new_talam_path
  .bread_crumbs= t(:talam)
  .clear

.body
  %table{:cellspacing => "0", :cellpadding => "0"}
    %thead
      %tr
        %th Name
        %th Avartanam
        %th Laghu Length
        %th
    %tbody
      - @talams.each do |talam|
        %tr>
          %td= link_to talam.name, talam_path(talam)
          %td= talam.avartanam
          %td= talam.laghu_length
          %td>
            [
            = link_to :edit, edit_talam_path(talam)
            ]

app/views/talams/new.html.haml
= render 'form', :talam => @talam, :form_title => "Create a new #{t :talam}"

app/views/talams/show.html.haml
.header
  .bread_crumbs="#{t(:talam)} #{@talam.name}"

.body
  .sidebar
    .flash_notice
    .error

  %dl
    %dt= t(:name)
    %dd= @talam.name
    %dt= t(:avartanam)
    %dd= @talam.avartanam
    %dt= t(:laghu_length)
    %dd= @talam.laghu_length