config/routes.rb
Karaharapriya::Application.routes.draw do

  devise_for :users

  root :to => "home#index"

  resources :ragams, :songs, :talams, :composers, :except => [:destroy]

  match "suggest/ragam" => "ragams#suggest", :as => "suggest_ragam"
  match "suggest/talam" => "talams#suggest", :as => "suggest_talam"
  match "suggest/composer" => "composers#suggest", :as => "suggest_composer"
end

app/models/ragam.rb
class Ragam
  include Mongoid::Document
  include Mongoid::Globalize
  include Suggest

  field :name, :type => Hash
  field :arohana
  field :avarohana
  referenced_in :parent, :class_name => "Ragam"
  attr_protected :_id

  validates_presence_of :name, :arohana, :avarohana
  validates_uniqueness_of :name
  validates_uniqueness_of :arohana, :scope => :avarohana
  validate :minimum_length
  translate :name

  scope :find_by_name, lambda { |name| where(:name => name) }

  def minimum_length
    errors.add(:base, "Arohana should have atleast 5 swaras") if !self.arohana.blank? && self.arohana.split(" ").count < 5
    errors.add(:base, "Avarohana should have atleast 5 swaras") if !self.avarohana.blank? && self.avarohana.split(" ").count < 5
  end

  def to_param
    self.name
  end

end

app/controllers/ragams_controller.rb
class RagamsController < AuthenticatableController

  before_filter :remove_first_class_params, :only => [:create, :update]
  before_filter :load_ragam, :only => [:edit, :update, :show]

  def index
    @ragams = Ragam.includes(:parent).all
  end

  def show
  end

  def new
    @ragam = Ragam.new
  end

  def create
    ragam = Ragam.create(params[:ragam])
    render_custom_response RemoteResponse.new(ragam, ragams_path)
  end

  def update
    @ragam.update_attributes(params[:ragam])
    render_custom_response RemoteResponse.new(@ragam, ragams_path)
  end

  def suggest
    render :partial => "common/suggest", :locals => { :suggestions => Ragam.suggest_by_name(params[:name]), :name => "ragam"}
  end

  private

  def remove_first_class_params
    [:parent].each {|key| params[:ragam].delete(key)}
  end

  def load_ragam
    @ragam = Ragam.find_by_translated_field("name", params[:id])
  end

end

app/views/ragams/_form.html.haml
= form_for ragam, :remote => true do |f|
  - parent_ragam_name = ragam.parent.nil? ? nil : ragam.parent.name

  .header
    .bread_crumbs= form_title

  .body
    .sidebar
      .flash_notice{"data-error-info" => "true"}
      .error{"data-error-display" => "true"}

    %dl
      %dt= f.label :name, t(:name)
      %dd= f.text_field :name
      %dt= f.label :arohana, t(:arohana)
      %dd= f.text_field :arohana
      %dt= f.label :avarohana, t(:avarohana)
      %dd= f.text_field :avarohana
    = auto_complete :label => t(:parent), :field_name => "parent", :name => "parent_id", :url => suggest_ragam_path, :value => parent_ragam_name, :form_helper => f
    = submit_tag t(:submit)
    .clear

app/views/ragams/edit.html.haml
- form_title = "Editing #{@ragam.name} #{t(:ragam).downcase}"
= render 'form', :ragam => @ragam, :form_title => form_title

app/views/ragams/index.html.haml
.header
  .action
    = link_to t(:new_ragam), new_ragam_path
  .bread_crumbs
  .clear

.body
  %table{:cellspacing => "0", :cellpadding => "0"}
    %thead
      %tr
        %th Name
        %th Arohana
        %th Avarohana
        %th Parent
        %th
    %tbody
      - @ragams.each do |ragam|
        %tr
          %td= link_to ragam.name, ragam_path(ragam)
          %td= ragam.arohana
          %td= ragam.avarohana
          %td= ragam.parent.nil? ? "" : ragam.parent.name
          %td
            = link_to :edit, edit_ragam_path(ragam)

app/views/ragams/new.html.haml
- form_title = "Create a new #{t :song}"
= render 'form', :ragam => @ragam, :form_title => form_title

app/views/ragams/show.html.haml
- parent_ragam_name = @ragam.parent.nil? ? nil : @ragam.parent.name

.header
  .bread_crumbs="#{t :ragam} #{@ragam.name}"

.body
  .sidebar
    .flash_notice
    .error
  %dl
    %dt= t(:name)
    %dd= @ragam.name
    %dt= t(:arohana)
    %dd= @ragam.arohana
    %dt= t(:avarohana)
    %dd= @ragam.avarohana
    %dt= t(:parent)
    %dd= parent_ragam_name